// <auto-generated />
using System;
using Ghaddoura_Imran_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ghaddoura_Imran_Project.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241221195425_ini")]
    partial class ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ghaddoura_Imran_Project.Models.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CourseName");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("Points");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe55fb8c-8272-4539-8a22-22a81e5ba1ec"),
                            CourseName = "Computer Science",
                            Points = 60,
                            StudentId = new Guid("196b8cd8-70de-4085-b35f-8a96c215f143")
                        },
                        new
                        {
                            Id = new Guid("abbc66b0-5e17-4850-bb6c-ba25b4ae848b"),
                            CourseName = "Mechanical Engineering",
                            Points = 45,
                            StudentId = new Guid("2614957e-ee64-4d37-9032-692ee9f3b3d5")
                        });
                });

            modelBuilder.Entity("Ghaddoura_Imran_Project.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("196b8cd8-70de-4085-b35f-8a96c215f143"),
                            FirstName = "Imran",
                            LastName = "Ghaddoura",
                            UniversityId = new Guid("15d7d52c-b339-403d-94ff-81c8b8f507de")
                        },
                        new
                        {
                            Id = new Guid("2614957e-ee64-4d37-9032-692ee9f3b3d5"),
                            FirstName = "Sara",
                            LastName = "De Vries",
                            UniversityId = new Guid("7406c7e1-0ca2-44c3-85c0-cad6f2c44b1d")
                        });
                });

            modelBuilder.Entity("Ghaddoura_Imran_Project.Models.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15d7d52c-b339-403d-94ff-81c8b8f507de"),
                            Location = "Amsterdam",
                            Name = "University of Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("7406c7e1-0ca2-44c3-85c0-cad6f2c44b1d"),
                            Location = "Delft",
                            Name = "Delft University of Technology"
                        });
                });

            modelBuilder.Entity("Ghaddoura_Imran_Project.Models.Result", b =>
                {
                    b.HasOne("Ghaddoura_Imran_Project.Models.Student", "Student")
                        .WithMany("Results")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Ghaddoura_Imran_Project.Models.Student", b =>
                {
                    b.HasOne("Ghaddoura_Imran_Project.Models.University", "University")
                        .WithMany("Students")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Ghaddoura_Imran_Project.Models.Student", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Ghaddoura_Imran_Project.Models.University", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
